### PR TITLE
Queue Fix and documentation update

### PR DESCRIPTION
**Pull request by rgovoni**
Fix for queuing

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, it looks like the key line reverses the `<` sign for `>` - was the rest of the queuing code already complete? and why would we want to add a file when there are more than the # of desired simultaneous downloads? Even if I'm misreading this code, do you think you could leave some comments inline to describe what's going on so it's more clear? Thanks!

**Comment by rgovoni** [comment]
I read through the queuing code and it looked fully set up to me--it just needed a sign switch so the queue would work. Before, if more than 9 images were selected for upload it would block any upload, but now if more than 9 are uploaded the additional images are moved into the queue. I sent it through for uploads of 15-45 images and it went through 9 at a time uploading and generating thumbnails. I can add a comment no worries. I may be misunderstanding but I think the queue was already fully set up but the sign was stopping any uploads from being put in the queue.

**Comment by jywarren** [comment]
Hmm, ok - I tested this on my laptop, a fairly minimal ASUS EEE with 2gb ram, and it crashed; I'll try it on a phone and on a more powerful Core i5 iMac.

**Comment by jywarren** [comment]
It worked on my phone; great. I'm actually on chromium on the netbook so I'm going to try it on chrome too.

**Comment by jywarren** [comment]
I've merged this in, but I'm still seeing crashes on both Chrome and Chromium; going to move back to the queuing issue to try to further address this.

**Pull request merged**
